Repository Avaiga/taipy-core, pull requests merged in 2022-06, with the labels that each got.

#227 Scenario lazy loading
  taipy/core/cycle/_cycle_manager.py
  taipy/core/scenario/_scenario_manager.py
  taipy/core/scenario/_scenario_repository.py
  taipy/core/scenario/scenario.py
Labels: back-end

#230 Update pandas version to 1.3
  Pipfile
  setup.py
Labels: devops, back-end

#231 Use panda 1.3.4 and not 1.3.5
  Pipfile
  setup.py
Labels: devops

#237 Fix - Add default_path default value
  taipy/core/config/config.py
Labels: bug, back-end

#252 Do not run dependencies anymore
  .github/workflows/run-dependencies.yml
Labels: devops
