Repository Avaiga/taipy-core, pull requests merged in 2022-08, with the labels that each got.

#281 Feature - Delete primary scenario
  src/taipy/core/scenario/_scenario_manager.py
  src/taipy/core/taipy.py
  tests/core/scenario/test_scenario_manager.py
Labels: Scenario Manager, Back-End

#289 fix failed test due to recursive call when raise NotMatchSheetNameAnd…
  src/taipy/core/data/excel.py
  tests/core/_scheduler/test_scheduler.py
Labels: Bug, Back-End

#300 Fix - KeyError in ExcelDataNode
  src/taipy/core/data/excel.py
Labels: Bug
