Repository Avaiga/taipy-core, pull requests merged in 2023-02, with the labels that each got.

#453 Fix/ Config conflict typo
  src/taipy/core/_version/_version_manager.py
  src/taipy/core/exceptions/exceptions.py
Labels: 💥Malfunction

#452 Fix/#414 Formatting version list with colors on supported terminal only
  src/taipy/core/_version/_bcolor.py
  src/taipy/core/_version/_version_cli.py
Labels: 🟩 Priority: Low, 💥Malfunction

#456 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature-improvement.md
  .github/ISSUE_TEMPLATE/new-feature.md
Labels: 🖧 Devops

#463 Refactor/#421 Refactor the behavior of Config.config_data_node() method
  src/taipy/core/config/data_node_config.py
  src/taipy/core/data/parquet.py
  tests/core/config/checkers/test_data_node_config_checker.py
  tests/core/config/test_config_serialization.py
  tests/core/config/test_configure_default_config.py
  tests/core/config/test_data_node_config.py
  tests/core/config/test_default_config.py
  tests/core/config/test_file_config.py
  tests/core/version/test_version_cli.py
Labels: 📈 Improvement

#485 Feat/ Improve Config.check() on Core
  src/taipy/core/config/checkers/_data_node_config_checker.py
  src/taipy/core/config/checkers/_job_config_checker.py
  src/taipy/core/config/checkers/_scenario_config_checker.py
  src/taipy/core/config/checkers/_task_config_checker.py
  src/taipy/core/config/data_node_config.py
  tests/core/config/checkers/test_data_node_config_checker.py
  tests/core/config/checkers/test_job_config_checker.py
  tests/core/config/checkers/test_pipeline_config_checker.py
  tests/core/config/checkers/test_scenario_config_checker.py
  tests/core/config/checkers/test_task_config_checker.py
  tests/core/config/test_data_node_config.py
  tests/core/test_core.py
Labels: 💥Malfunction, 📈 Improvement
